params:
  logo: 
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  gutter: 24
  container:
    desktop: 1292
    mobile: 300
  hero:
    desktop: "416x"
    mobile: "300x"
  image:
    xlarge: "1600x"
    xsmall: "50x50"
    desktop: "856x"
    mobile: "300x"
    scrollsnap: "240x"
  thumbnail:
    desktop: "414x177"
    mobile: "300x129"
    scrollsnap: "240x103"

  pages:
    thumbnail:
      desktop: "414x177"
      mobile: "300x129"
      scrollsnap: "240x103"
    image:
      desktop: "856x"
      mobile: "300x"
  blocks:
    editorial:
      desktop: "624x"
      mobile: "300x"
    figure:
      desktop: "1292x"
      mobile: "300x"
    gallery:
      mobile: "138x138"
  