params:
  logo: 
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  gutter: 24
  container:
    desktop: 1292
    mobile: 330
  image:
    xlarge: "1600x"
    xsmall: "50x50"
    desktop: "856x"
    mobile: "330x"
  authors:
    thumbnail:
      desktop: "100x100"
    image:
      desktop: "100x100"
    post:
      desktop: "50x50"
  pages:
    thumbnail:
      desktop: "414x177"
      mobile: "330x142"
    image:
      desktop: "856x"
      mobile: "330x"
  posts:
    thumbnail:
      desktop: "414x177"
      mobile: "330x142"
    image:
      desktop: "856x"
      mobile: "330x"
  projects:
    thumbnail:
      desktop: "414x312"
      mobile: "330x248"
    image:
      desktop: "856x"
      mobile: "330x"
  casestudies:
    thumbnail:
      desktop: "414x177"
      mobile: "330x142"
    image:
      desktop: "856x"
      mobile: "330x"
  publications:
    thumbnail:
      desktop: "306x459"
      mobile: "156x234"
    image:
      desktop: "746x"
      mobile: "330x"
  blocks:
    editorial:
      desktop: "624x"
      mobile: "330x"
    figure:
      desktop: "1292x"
      mobile: "330x"
    gallery:
      mobile: "330x"
  