module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
  imports:
    # Import bootstrap 5
    - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
    # Import bootstrap icons
    - path: github.com/twbs/icons
      mounts:
        - source: font/fonts
          target: static/assets/fonts/bootstrap-icons
    # Import lightbox plugin
    - path: github.com/midzer/tobii
      mounts:
        - source: src/scss
          target: assets/scss/tobii
        - source: src/js
          target: assets/js/vendors/tobii
    # Import instafeed
    - path: github.com/stevenschobert/instafeed.js
      mounts:
        - source: src
          target: assets/js/vendors/instafeed

# Params
params:
  logo: 
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  gutter: 24
  container:
    desktop: 1292
    mobile: 300
  hero:
    desktop: "416x"
    mobile: "300x"
  image:
    xlarge: "1600x"
    xsmall: "50x50"
    desktop: "856x"
    mobile: "300x"
    scrollsnap: "240x"
  thumbnail:
    desktop: "414x177"
    mobile: "300x129"
    scrollsnap: "240x103"
  pages:
    thumbnail:
      desktop: "414x177"
      mobile: "300x129"
      scrollsnap: "240x103"
    image:
      desktop: "856x"
      mobile: "300x"
  blocks:
    editorial:
      desktop: "624x"
      mobile: "300x"
    figure:
      desktop: "1292x"
      mobile: "300x"
    gallery:
      mobile: "138x138"

# Privacy
privacy:
  instagram:
    simple: false
  twitter:
    enableDNT: true
    simple: false
  vimeo:
    enableDNT: true
    simple: false
  youtube:
    privacyEnhanced: true

# Services
services:
  instagram:
    disableInlineCSS: false
  twitter:
    disableInlineCSS: false
