params:
  logo: "/assets/images/logo.svg"
  gutter: 24
  container:
    desktop: 1292
    mobile: 336
  image:
    xlarge: "1600x"
    desktop: "856x"
    mobile: "336x"
  authors:
    thumbnail:
      desktop: "100x100"
    image:
      desktop: "100x100"
    post:
      desktop: "50x50"
  posts:
    thumbnail:
      desktop: "414x177"
      mobile: "336x144"
    image:
      desktop: "856x"
      mobile: "336x"
  projects:
    thumbnail:
      desktop: "414x312"
      mobile: "336x250"
    image:
      desktop: "856x"
      mobile: "336x"
  casestudies:
    thumbnail:
      desktop: "414x177"
      mobile: "336x144"
    image:
      desktop: "856x"
      mobile: "336x"
  publications:
    thumbnail:
      desktop: "306x459"
      mobile: "156x234"
    image:
      desktop: "746x"
      mobile: "336x"
  blocks:
    editorial:
      desktop: "624x"
      mobile: "336x"
    figure:
      desktop: "1292x"
      mobile: "336x"
    gallery:
      mobile: "336x"
  